### ISSUE TITLE
Refactoring gprtXYZBufferCreate...

### ISSUE THREAD

**Issue by natevm** [gprt-org/GPRT#1]
We should refactor the current gprtXYZBufferCreate functions.

At the moment, we have two functions, 
`gprtDeviceBufferCreate` and `gprtHostPinnedBufferCreate`. 
These functions come from our previous OptiX framework "owl", which use CUDA for it's memory management.

The issue I have with the name of these functions is that they do not align properly with how Vulkan handles memory.
Here's a good breakdown of Vulkan's memory model for different GPU vendors: https://asawicki.info/news_1740_vulkan_memory_types_on_pc_and_how_to_use_them

In CUDA, if someone makes a cuda buffer with `cudaMalloc`, then end users upload data from the host to the device with `cudaMemcpy` and specify that the transfer is from host to device, or from device to host. But in Vulkan, that's not really possible.

Instead, with Vulkan we must create a host pinned "staging" buffer and then a device buffer, then copy data from host into the staging buffer, then from the staging buffer into the device buffer. 

We abstract this away from the user, and allocate both a vulkan device side buffer and a vulkan host side staging buffer whenever we call `gprtDeviceBufferCreate`.  And by doing that, we can also allow users to "pin" device buffers using `gprtBufferMap` and `gprtBufferUnmap`, which under the hood facilitate this transfer from the vulkan host-side staging buffer to the vulkan device-side buffer. So therefore, I'd argue that we should drop the "pinned" part of `gprtHostPinnedBufferCreate`, since we allow all buffers to be pinned as far as the end user is concerned.

Then finally, Vulkan has a mechanism to expose sections of GPU memory that are visible to both the host as well as the device, through a feature called BAR. If a system has "Resizable BAR", this allocation can be whatever you want, and otherwise, modern GPU architectures expose 256MB of BAR memory. I'd like to expose this functionality, so we need to extend the API to allow for this. So we're thinking of creating a function called `gprtSharedBufferCreate`, which creates a device side buffer accessible to both the host and device, which is fast, but also potentially limited in size.

**Comment by pshriwise** [comment]
Resolved by #9
