### ISSUE TITLE
Update readme and CI to drop custom dxc compiler

### ISSUE THREAD

**Issue by natevm** [gprt-org/GPRT#17]
With the latest Vulkan SDK, we no longer need users to use a custom version of dxc. To make setup easier, we should drop the mention of the custom dxc version from the readme, and also should remove it from the CI machines in favor of the dxc that comes with the vulkan SDK

**Comment by pshriwise** [comment]
Is there a Vulkan SDK release to reference at this point?

**Comment by natevm** [comment]
We could just go with latest, 1.3.231.1 should work
