### ISSUE TITLE
cmake: dxc not found

### ISSUE THREAD

**Issue by tigrazone** [gprt-org/GPRT#26]
I have Windows 10 and MinGW.
I do cmake  .. -G "Unix Makefiles"
as always
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Using module to find Vulkan
-- Found Vulkan: C:/VulkanSDK/1.3.211.0/Lib/vulkan-1.lib
-- C:/VulkanSDK/1.3.211.0/Lib/vulkan-1.lib
-- Found OpenGL: opengl32  found components: OpenGL
CMake Error at gprt/cmake/embed_devicecode.cmake:35 (message):
  dxc not found.
Call Stack (most recent call first):
  gprt/CMakeLists.txt:27 (include)

-- Configuring incomplete, errors occurred!
How to fix this error?

**Comment by tigrazone** [comment]
I use cmake 3.21.0
Vulkan SDK 1.3.211.0

**Comment by natevm** [comment]
Hey @tigrazone were you able to solve this issue by updating your cmake cache?

**Comment by tigrazone** [comment]
No. Same errors

**Comment by natevm** [comment]
What errors?

**Comment by natevm** [comment]
Also, again, your Vulkan SDK is out of date. We require 1.3.231.1 or newer. You are using 1.3.2**1**1.1

**Comment by natevm** [comment]
@tigrazone we just got a PR into master with some updated CMake hints to help find DXC.exe. After updating your Vulkan SDK, would you be willing to test and see if you still run into this issue on the latest commit to master?

**Comment by natevm** [comment]
I'm assuming this issue has been resolved, so I'll close the issue for now. Please let me know if it's still something troubling you. :)
