### ISSUE TITLE
Problem compiling with Vulkan SDK version 1.3.261.1

### ISSUE THREAD

**Issue by pshriwise** [gprt-org/GPRT#75]
![image](https://github.com/gprt-org/GPRT/assets/4563941/d065a1da-7f53-44fe-860d-3c2dc2d9733a)

**Comment by natevm** [comment]
Unfortunately i think this is a CMake issue on linux. Apparently Ubuntu ships with a very outdated version of the dxc compiler, which is added to the path by default. 

However, we need to explicitly select the dxc version that comes with the Vulkan SDK in the bin folder.

**Comment by pshriwise** [comment]
Strange, it seems to work fine with 1.3.250.1. I reverted to that version b/c it's the one used in CI. Though I do recall that being an issue...

**Comment by natevm** [comment]
I can try to update on my machine and see if I can reproduce locally.

**Comment by natevm** [comment]
@pshriwise could you try to test this out again with latest GPRT? I have a fix pushed to master now that I believe fixes the issue. 

There was a change with DXC on trunc that unfortunately caused a regression... The change is that we now are locked into a more stable DXC version, which we download as part of the cmake configure step.

**Comment by pshriwise** [comment]
Confirmed fixed 👍🏻 on Linux
